name: "edit-n2n-kitti"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0
 
data_type: "gs-load-kitti"
data:
  batch_size: 1
  source: "/DATA1/zhuyunwei/KITTI-360"
  max_view_num: 10 # 96
  eval_camera_distance: 4.0
  camera_distance_range: [1.5, 60] # TODO Camera distance range to sample from in training
  light_sample_strategy: "dreamfusion3dgs"
  height: 512
  width: 512

  elevation_view_num: 2
  azimuth_view_num: 8
  seq: 0
  chunk_id: 22
  # elevation_range: [-10 , 80]
trainer:
  max_steps: 6000
  log_every_n_steps: 10
  num_sanity_val_steps: 0
  val_check_interval: 20
  enable_progress_bar: true
  precision: 16-mixed
system_type: "gsedit-system-edit"
system:
  gs_source: "/home/zhuyunwei/GaussianEditor/gaussiansplatting/output/20240510_221252_save/point_cloud/iteration_50000/point_cloud.ply"
  sky_source: "/home/zhuyunwei/GaussianEditor/gaussiansplatting/output/20240510_221252_save/chkpnt50000_sky.pth"

  per_editing_step: 10
  edit_begin_step: 0
  edit_until_step: 50000
  densify_until_iter: 40000
  densify_from_iter: 0
  densification_interval: 1500
  max_grad: 5
  min_opacity: 0.005
  seg_prompt: ""
  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
    prompt: 'make it snowy'
  
  include_feature: false
  mask_thres: 0.8
  max_densify_percent: 0.01
  anchor_weight_init_g0: 0.01
  anchor_weight_init: 0.1
  anchor_weight_multiplier: 1.3
  gs_lr_scaler: 0.1
  gs_final_lr_scaler: 0.1
  color_lr_scaler: 1
  rotation_lr_scaler: 1 # 2

  guidance_type: "stable-diffusion-instructpix2pix-guidance"
  guidance:
    min_step_percent: 0.02
    max_step_percent: 0.98
    guidance_scale: 8
    condition_scale: 1

  loggers:
    wandb:
      enable: false
      project: 'threestudio_gs'
      name: None

  loss:
#    lambda_opaque: 0.0
    lambda_sparsity: 0.0
    lambda_opaque: 0.0
    lambda_l1: 10.
    lambda_p: 10.
    lambda_dds: 0.
    lambda_anchor_color: 0
    lambda_anchor_geo: 50
    lambda_anchor_opacity: 50
    lambda_anchor_scale: 50
    lambda_move: 0
    lambda_alpha: 0
    lambda_scale: 0

  optimizer:
    name: Adam
    args:
      lr: 0.001
      betas: [0.9, 0.99]
      eps: 1.e-15
checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}

# white_background: true